theme: jekyll-theme-minimal
title: Denis Narush
logo: https://avatars0.githubusercontent.com/u/2277140
name: Denis Narush
description: Front-End Developer from Belarus. Have more than 10 years of commercial and 3 years of mentoring experience.
