theme: jekyll-theme-minimal
title: Denis Narush - Developer
name: Denis Narush
description: Front-End Developer from Belarus. Have more than 9 years of commercial and 3 years of mentoring experience.
google_analytics: UA-144291689-1
